### ISSUE TITLE
Doesn't Compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by pepa65** [kuba-moo/mt7601u#58]
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-42-generic'
  LD      /home/andrew/git/mt7601u/built-in.o
  CC [M]  /home/andrew/git/mt7601u/usb.o
  CC [M]  /home/andrew/git/mt7601u/init.o
  CC [M]  /home/andrew/git/mt7601u/main.o
/home/andrew/git/mt7601u/main.c:415:18: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ampdu_action = mt76_ampdu_action,
                  ^
/home/andrew/git/mt7601u/main.c:415:18: note: (near initialization for ‘mt7601u_ops.ampdu_action’)
cc1: all warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/andrew/git/mt7601u/main.o' failed
make[2]: **\* [/home/andrew/git/mt7601u/main.o] Error 1
Makefile:1403: recipe for target '_module_/home/andrew/git/mt7601u' failed
make[1]: **\* [_module_/home/andrew/git/mt7601u] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-42-generic'
Makefile:8: recipe for target 'default' failed
make: **\* [default] Error 2
