### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by garisha** [kuba-moo/mt7601u#29]
$ make
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory `/usr/src/linux-headers-3.13.0-53-generic'
  CC [M]  /home/garisha/Downloads/mt7601u-master/init.o
/home/garisha/Downloads/mt7601u-master/init.c: In function ‘mt76_init_sband’:
/home/garisha/Downloads/mt7601u-master/init.c:533:2: error: implicit declaration of function ‘devm_kmemdup’ [-Werror=implicit-function-declaration]
  chanlist = devm_kmemdup(dev->dev, chan, size, GFP_KERNEL);
  ^
/home/garisha/Downloads/mt7601u-master/init.c:533:11: error: assignment makes pointer from integer without a cast [-Werror]
  chanlist = devm_kmemdup(dev->dev, chan, size, GFP_KERNEL);
           ^
cc1: all warnings being treated as errors
make[2]: *** [/home/garisha/Downloads/mt7601u-master/init.o] Error 1
make[1]: *** [_module_/home/garisha/Downloads/mt7601u-master] Error 2
make[1]: Leaving directory`/usr/src/linux-headers-3.13.0-53-generic'
make: **\* [default] Error 2

**Comment by kuba-moo** [comment]
You have 3.13 kernel, this driver works with 3.19 and newer. Please read README.
